name: Schema

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7
        with:
          ref: ${{ github.head_ref }}

      - name: Install Rust
        uses: dtolnay/rust-toolchain@6bed0761d98439e5a578e2877258200ad565ba87 # stable

      - name: Cache cargo dependencies
        uses: Swatinem/rust-cache@6323deb102c322ba6fcbdcafc7e3dddab59af2b6 # v2

      - name: Setup other tools
        uses: jdx/mise-action@c2a87611a18de5b3828c5652fe268e992400cb5c # v4

      - name: Generate schema.json
        run: cargo run --bin firepit-schema

      - name: Generate schema-body.md
        run: ./scripts/schema-to-md.js schema.json docs/schema-body.md

      - name: Configure git
        uses: kota65535/github-git-config-action@519e6d26e10ccdd2ac3437dd5ed32c4042583f09 # v2
        with:
          user.name: github-actions[bot]
          user.email: 41898282+github-actions[bot]@users.noreply.github.com
          github-token: ${{ secrets.PERSONAL_TOKEN }}

      - name: Diff
        id: diff
        run: |
          git add -N .
          git diff --name-only --exit-code
        continue-on-error: true
      - name: Commit & Push
        if: steps.diff.outcome == 'failure'
        run: |
          git add .
          git commit --author=. -m 'chore(schema): generate'
          git pull --rebase --autostash
          git push origin HEAD
